// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("ORDER_ITEM")]
public partial class OrderItem
{
    [Key]
    [Column("ORDER_ITEM_ID")]
    public int OrderItemId { get; set; }

    [Column("PRODUCT_ID")]
    public int ProductId { get; set; }

    [Column("ORDER_ID")]
    public int OrderId { get; set; }

    [Column("QUANTITY")]
    public int Quantity { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItems")]
    //[JsonIgnore]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderItems")]
    //[JsonIgnore]
    public virtual Product Product { get; set; }
}