// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("PRODUCTS")]
public partial class Product
{
    [Key]
    [Column("PRODUCT_ID")]
    public int ProductId { get; set; }

    [Required]
    [Column("PRODUCT_NAME")]
    [StringLength(50)]
    public string ProductName { get; set; }

    [Column("PRICE")]
    public double Price { get; set; }

    [Column("CATEGORY_ID")]
    public int CategoryId { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(50)]
    public string Description { get; set; }

    [Column("IMAGE_URL")]
    [StringLength(50)]
    public string ImageUrl { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    //[JsonIgnore]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}