// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("USERS")]
public partial class User
{
    [Key]
    [Column("USER_ID")]
    public int userId { get; set; }

    [Required]
    [Column("USERNAME")]
    [StringLength(50)]
    public string userName { get; set; }

    [Required]
    [Column("PASSWORD")]
    [StringLength(50)]
    public string password { get; set; }

    [Column("FIRSTNAME")]
    [StringLength(50)]
    public string firstName { get; set; }

    [Column("LASTNAME")]
    [StringLength(50)]
    public string lastName { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}